# Generated by Django 2.2.4 on 2020-02-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omgwords-agent', '0012_coin_side'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
