# Generated by Django 2.2.4 on 2020-04-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omgwords-agent', '0018_websiteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
